project:
  type: website

website:
  title: "M Dims blog"
  google-analytics: "G-5TD5B2PHN7"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dimitra-maoutsa
      - icon: twitter
        href: https://https://bsky.app/profile/dimma.bsky.social

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



